### ISSUE TITLE
client.js:1 mintUserToken tx failed Error: signer already added before

### ISSUE THREAD

**Issue by besiwims** [lley154/atomic-swap-open-protocol#4]
When I add User Info with Nami wallet I get this error below  and does not proceed from this point:

client.js:1 mintUserToken tx failed Error: signer already added before
    at assert (helios.js:420:1)
    at TxBody.addSigner (helios.js:42896:1)
    at Tx.addSigner (helios.js:41724:1)
    at mintUserToken (index.tsx:363:10)
console.error @ client.js:1
window.console.error @ next-dev.js:27
mintUserToken @ index.tsx:387
await in mintUserToken (async)
onSubmit @ MintUserToken.tsx:10
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
index.tsx:389 Uncaught (in promise) undefined
mintUserToken @ index.tsx:389
await in mintUserToken (async)
onSubmit @ MintUserToken.tsx:10
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430

**Comment by lley154** [comment]
as discussed, there appears to be some error when Nami is returning the signatures for some combination of tokens.   I am not able to reproduce, but let's keep this open in cases there are other reported errors.
